
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/freshkhao
hooks:
  ApplicationStop:
    - location: applicationstop.sh
      timeout: 300
  Install:   
    - location: install.sh
      timeout: 300     
  AfterInstall:   
    - location: afterinstall.sh
      timeout: 300    
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 300
   
